---
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 5 # 4
  file-lines:
    enabled: false # true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 10 #5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 100 # 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 60 #28
  identical-code:
    enabled: true
    config:
      threshold: 28

plugins:
  rubocop:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false  
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: false
    config:
      ignore_warnings: true
      encoding: utf-8"
  sonar-php:
    enabled: true
    config:
      minimum_severity: critical
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      
exclude_patterns:
  - vendor/
  - js/jquery*
  - js/tinymce*
  - js/tinymce5/
  - cache/
  - files/
  - images/
  - log/
  - nbproject/
  - var/