include:
  - template: Code-Quality.gitlab-ci.yml
#  - template: Secret-Detection.gitlab-ci.yml

stages:
  - test 
  - staging

code_quality:
# https://gitlab.alembiq.net/help/user/project/merge_requests/code_quality#code-quality-reports
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
    - if: '$CI_PIPELINE_SOURCE == "web"' # Run code quality job in pipelines started from gitlab UI
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the master branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_TAG'                               # Run code quality job in pipelines for tags

code_quality_html:
  stage: test
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
    expire_in: 3 months
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
    - if: '$CI_PIPELINE_SOURCE == "web"' # Run code quality job in pipelines started from gitlab UI
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the master branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_TAG'                               # Run code quality job in pipelines for tags

#secret_detection:
#  stage: test
#  allow_failure: true
#  variables:
#    SECRET_DETECTION_HISTORIC_SCAN: "true"
# https://www.youtube.com/watch?time_continue=50&v=B32LxtJKo9M

#static_analysis:
#  stage: test
#  image: php:7.2-fpm
#  before_script:
#    - wget https://github.com/phpstan/phpstan/releases/download/0.11.19/phpstan.phar -O bin/phpstan.phar
#  script:
#    - php bin/phpstan.phar --error-format gitlab  analyse src --level=1

test to bistro.alembiq.net:
  image: debian:latest
  stage: staging
  before_script: 
    - DEBIAN_FRONTEND="noninteractive"
    - 'which ssh-agent || ( apt update -y && apt install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - ssh-keyscan $CI_ENVIRONMENT_URL >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
  script:
    - echo "Deploy to staging $URL"
    - chmod 600 $SSH_KEY
    - cat $SSH_KEY | tr -d '\r' | ssh-add -
    - export
    - ssh gitlab-ci@$CI_ENVIRONMENT_URL "cd /srv/net.alembiq.bistro/htdocs && git reset --hard && git remote set-url gitlab $CI_REPOSITORY_URL && git pull gitlab $CI_COMMIT_SHA && exit"
  environment:
    name: staging
    url: bistro.alembiq.net
  rules: 
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"  &&  $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
    - when: never