stages:
  - test 
  - deploy

#https://gitlab.com/frakman1/codeclimate-test/blob/master/.gitlab-ci.yml
code_quality-html:
  stage: test
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
    CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/security-products/codequality:0.85.6"
  script:
    - |
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    - docker run
        --env CONTAINER_TIMEOUT_SECONDS=1800
        --env CODECLIMATE_CODE="$PWD" 
        --env CODECLIMATE_DEBUG=0
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        --volume /tmp/cc:/tmp/cc 
       codeclimate/codeclimate:0.85.6 analyze -f html > report.html
  artifacts:
    paths: [report.html]
    expire_in: 10 weeks
  dependencies: []
  only:
    - merge_requests
#    - web
  except:
    variables:
      - $CODE_QUALITY_DISABLED



code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --env CODECLIMATE_DEBUG=0
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  only:
    - merge_requests
#    - web
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths: [gl-code-quality-report.json]
    expire_in: 10 weeks

#static_analysis:
#  stage: test
#  image: php:7.2-fpm
#  before_script:
#    - wget https://github.com/phpstan/phpstan/releases/download/0.11.19/phpstan.phar -O bin/phpstan.phar
#  script:
#    - php bin/phpstan.phar --error-format gitlab  analyse src --level=1


deploy_staging:
  image: debian:latest
  stage: deploy
  before_script: 
    - DEBIAN_FRONTEND="noninteractive"
    - 'which ssh-agent || ( apt update -y && apt install openssh-client -y )'
    - eval $(ssh-agent -s)
    - export
    - cat "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo "$CI_ENVIRONMENT_URL" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploy to staging"
    - ssh root@$CI_ENVIRONMENT_URL "cd /srv/bistro.alembiq.net/htdocs && git checkout master && git pull origin master && exit"
    - export 
#  - ssh -p22 server_user@server_host "mkdir htdocs/wp-content/themes/_tmp"
# ssh-add <(echo "$STAGING_PRIVATE_KEY")
# ssh gitlab@alembiq.net
# git remote add  -f $CI_COMMIT_SHA $CI_REPOSITORY_URL
# git pull $CI_COMMIT_SHA $CI_COMMIT_BRANCH
  environment:
    name: staging
    url: alembiq.net
  only: 
    - merge_requsets
    - web
#    - master

