# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Code-Quality.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
variables:
  SAST_EXPERIMENTAL_FEATURES: 'true'
  SAST_DEFAULT_ANALYZERS: nodejs-scan,eslint,phpcs-security-audit
  SEARCH_MAX_DEPTH: 10

stages:
- build
- test
- deploy

build:
  stage: build
  image: alpine
  before_script:
  - apk add gzip
  - apk add composer
  script:
  - composer install --ignore-platform-reqs
  - composer update --ignore-platform-reqs
  - tar czf build.tgz --exclude .git --exclude bistro.tmp .
  artifacts:
    paths:
    - build.tgz
    expire_in: 1 days
  rules:
  - when: always

code_quality:
  stage: test
  interruptible: true
  artifacts:
    paths:
    - gl-code-quality-report.json
  rules:
  - if: "$CODE_QUALITY_DISABLED"
    when: never
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  - if: "$CI_COMMIT_TAG"

sast:
  stage: test
  variables:
    SAST_EXCLUDED_PATHS: vendor, js/jquery*, js/tiny*
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, gosec, kubesec, nodejs-scan,
      pmd-apex, security-code-scan, sobelow, spotbugs

deploy alembiq:
  stage: deploy
  image: alpine
  needs:
  - build
  allow_failure: true
  before_script:
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - cat $SSH_ALEMBIQ | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan alembiq.net >> ~/.ssh/known_hosts
  script:
  - scp build.tgz gitlab-ci@alembiq.net:.
  - ssh gitlab-ci@alembiq.net "mkdir $ALEMBIQ_FOLDER/$CI_JOB_ID
    && tar zxf build.tgz -C $ALEMBIQ_FOLDER/$CI_JOB_ID/
    && cp $ALEMBIQ_FOLDER/htdocs/.env.php $ALEMBIQ_FOLDER/$CI_JOB_ID/
    && rsync -au --remove-source-files $ALEMBIQ_FOLDER/htdocs/files/ $ALEMBIQ_FOLDER/$CI_JOB_ID/files/
    && tar zcf $ALEMBIQ_FOLDER/backup-$CI_JOB_ID.tgz --exclude $ALEMBIQ_FOLDER/htdocs/cache --exclude $ALEMBIQ_FOLDER/htdocs/.git $ALEMBIQ_FOLDER/htdocs/
    && mv $ALEMBIQ_FOLDER/htdocs $ALEMBIQ_FOLDER/backup
    && mv $ALEMBIQ_FOLDER/$CI_JOB_ID $ALEMBIQ_FOLDER/htdocs
    && rm -rf $ALEMBIQ_FOLDER/backup
    && rm build.tgz"
  only:
    - merge_requests

deploy nh_text:
  stage: deploy
  image: alpine
  needs:
  - build
  allow_failure: false
  before_script:
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - cat $SSH_TEST | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan nh.test.prazskahlidka.cz >> ~/.ssh/known_hosts
  script:
  - scp build.tgz prazskahlidka@nh.test.prazskahlidka.cz:.
  - ssh prazskahlidka@nh.test.prazskahlidka.cz "mkdir /srv/cz.prazskahlidka.test.nh/$CI_JOB_ID
    && tar zxf build.tgz -C /srv/cz.prazskahlidka.test.nh/$CI_JOB_ID/
    && find /srv/cz.prazskahlidka.test.nh/$CI_JOB_ID/ -type f  -not -regex '/srv/cz.prazskahlidka.test.nh/$CI_JOB_ID/\(vendor\|.git\|files\|js\|images\|custom\)/.*' -exec sed -i -r 's+Debugger::(DETECT|PRODUCTION)+Debugger::DEVELOPMENT+g' {} \;
    && cp /srv/cz.prazskahlidka.test.nh/htdocs/.env.php /srv/cz.prazskahlidka.test.nh/$CI_JOB_ID/
    && rsync -au --remove-source-files /srv/cz.prazskahlidka.test.nh/htdocs/files/ /srv/cz.prazskahlidka.test.nh/$CI_JOB_ID/files/
    && mv /srv/cz.prazskahlidka.test.nh/htdocs /srv/cz.prazskahlidka.test.nh/backup
    && mv /srv/cz.prazskahlidka.test.nh/$CI_JOB_ID /srv/cz.prazskahlidka.test.nh/htdocs
    && tar zcf /srv/cz.prazskahlidka.test.nh/backup-$CI_JOB_ID.tgz --exclude /srv/cz.prazskahlidka.test.nh/backup/cache /srv/cz.prazskahlidka.test.nh/backup/
    && rm -rf /srv/cz.prazskahlidka.test.nh/backup
    && rm build.tgz"
  only:
    - testing

deploy dh_text:
  stage: deploy
  image: alpine
  needs:
  - build
  allow_failure: false
  before_script:
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - cat $SSH_TEST | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan dh.test.prazskahlidka.cz >> ~/.ssh/known_hosts
  script:
  - scp build.tgz prazskahlidka@dh.test.prazskahlidka.cz:.
  - ssh prazskahlidka@dh.test.prazskahlidka.cz "mkdir /srv/cz.prazskahlidka.test.dh/$CI_JOB_ID
    && tar zxf build.tgz -C /srv/cz.prazskahlidka.test.dh/$CI_JOB_ID/
    && find /srv/cz.prazskahlidka.test.dh/$CI_JOB_ID/ -type f  -not -regex '/srv/cz.prazskahlidka.test.dh/$CI_JOB_ID/\(vendor\|.git\|files\|js\|images\|custom\)/.*' -exec sed -i -r 's+Debugger::(DETECT|PRODUCTION)+Debugger::DEVELOPMENT+g' {} \;
    && cp /srv/cz.prazskahlidka.test.dh/htdocs/.env.php /srv/cz.prazskahlidka.test.dh/$CI_JOB_ID/
    && rsync -au --remove-source-files /srv/cz.prazskahlidka.test.dh/htdocs/files/ /srv/cz.prazskahlidka.test.dh/$CI_JOB_ID/files/
    && mv /srv/cz.prazskahlidka.test.dh/htdocs /srv/cz.prazskahlidka.test.dh/backup
    && mv /srv/cz.prazskahlidka.test.dh/$CI_JOB_ID /srv/cz.prazskahlidka.test.dh/htdocs
    && tar zcf /srv/cz.prazskahlidka.test.dh/backup-$CI_JOB_ID.tgz --exclude /srv/cz.prazskahlidka.test.dh/backup/cache /srv/cz.prazskahlidka.test.dh/backup/
    && rm -rf /srv/cz.prazskahlidka.test.dh/backup
    && rm build.tgz"
  only:
    - testing
