# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Code-Quality.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
# - template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
variables:
  SAST_EXPERIMENTAL_FEATURES: 'true'
  SAST_DEFAULT_ANALYZERS: nodejs-scan,eslint,phpcs-security-audit
  SEARCH_MAX_DEPTH: 10
stages:
- build
- test
- deploy

build:
  stage: build
  image: alpine
  before_script:
  - apk add gzip
  - apk add composer
  script:
  - composer install --ignore-platform-reqs
  - composer update --ignore-platform-reqs
  - tar czf build.tgz --exclude .git --exclude bistro.tmp .
  artifacts:
    paths:
    - build.tgz
    expire_in: 1 days
  rules:
  - when: always

code_quality:
  stage: test
  interruptible: true
  artifacts:
    paths: [gl-code-quality-report.json]
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the default branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_TAG'

sast:
  stage: test
  variables:
    SAST_EXCLUDED_PATHS: vendor

deploy test:
  stage: deploy
  image: alpine
  needs:
  - build
  allow_failure: true
  before_script:
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - cat $SSH_KEY | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan alembiq.net >> ~/.ssh/known_hosts
  script:
  - scp build.tgz gitlab-ci@alembiq.net:.
  - ssh gitlab-ci@alembiq.net "mkdir $DEPLOY_FOLDER/$CI_JOB_ID
    && tar zxf build.tgz -C $DEPLOY_FOLDER/$CI_JOB_ID/
    && cp $DEPLOY_FOLDER/htdocs/.env.php $DEPLOY_FOLDER/$CI_JOB_ID/
    && rsync -au --remove-source-files $DEPLOY_FOLDER/htdocs/files/ $DEPLOY_FOLDER/$CI_JOB_ID/files/
    && tar zcf $DEPLOY_FOLDER/backup-$CI_JOB_ID.tgz --exclude $DEPLOY_FOLDER/htdocs/cache --exclude $DEPLOY_FOLDER/htdocs/.git $DEPLOY_FOLDER/htdocs/
    && mv $DEPLOY_FOLDER/htdocs $DEPLOY_FOLDER/backup
    && mv $DEPLOY_FOLDER/$CI_JOB_ID $DEPLOY_FOLDER/htdocs
    && rm -rf $DEPLOY_FOLDER/backup
    && rm build.tgz"
  rules:
  - when: manual
