version: "3.8"
services:

  # PHP Service
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    volumes:
      - ./source/:/var/www/html/
    user: 1111:1111
    depends_on:
      - mariadb

  # Apache Service
  apache:
    build: ./docker/apache/
    ports:
      - 80:80
    volumes:
      - ./source/:/var/www/html/
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: bistro
      MYSQL_PASSWORD: bistro
      MYSQL_DATABASE: bistro
    volumes:
      - mysqldata:/var/lib/mysql

  # Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb

# Volumes
volumes:
  mysqldata:
