version: "3.8"
services:

  # PHP Service
  php:
    build: './php/'
    volumes:
      - ../source/:/var/www/html/
    user: 1111:1111

  # Apache Service
  apache:
    build: './apache/'
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ../source/:/var/www/html/


  # MariaDB Service
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bistro
      MYSQL_PASSWORD: bistro
      MYSQL_DATABASE: bistro
    volumes:
      - mysqldata:/var/lib/mysql

  # Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb


# Volumes
volumes:
  mysqldata:
