#!/usr/bin/sh
# possible improvements https://github.com/BernardoSilva/git-hooks-php/blob/master/pre-commit

# https://github.com/symplify/easy-coding-standard
ECS="./source/vendor/bin/ecs"
ECS_CONFIG="ecs.php"
PHPCS="./source/vendor/bin/php-cs-fixer"
LATTE="./source/vendor/bin/latte-lint"
FILES=` git status --porcelain | grep -e '^[AM]\(.*\).php\|^[AM]\(.*\).md$' | cut -c 3- | tr '\n' ' '`


# https://victoria.dev/blog/an-automatic-interactive-pre-commit-checklist-in-the-style-of-infomercials/
exec < /dev/tty

function install_tools()
{
    sudo apt -qq -y install composer
    composer install
    composer require --dev symplify/easy-coding-standard
    composer require --dev friendsofphp/php-cs-fixer
}

echo "### LINTERS pre-commit hook start ###"

if [ ! -x $ECS ] || [ ! -x $LATTE ]; then
    while read -p "No validation tools found, should I install them? (Y/n) " yn; do
        case $yn in
            [Yy] ) install_tools;;
            [Nn] ) exit 1;;
            * ) echo "Please answer y (yes) or n (no):" && continue;
        esac
    done
fi

if [ -x $ECS ] && [ -x $LATTE ] && [ -x $PHPCS ] && [ -n "$FILES" ]; then
    echo "### PHP LINTER ###"
    $ECS check --config=$ECS_CONFIG $FILES --fix
    $PHPCS fix $FILES
    git add $FILES
    echo "### LATTE LINTER  ###"
    $LATTE ./templates
fi

echo "### LINTER pre-commit hook finish ###"

exec <&-
