<?php
$text['point']='zlobod';
$text['menu-zlobody']='Zlobody';
$text['hlaseniV']='Hlášení';
$text['hlaseniM']='hlášení';
$text['jmeno']='Jméno';
$text['heslo']='Heslo';
$text['prihlasit']='Přihlásit';
$text['bistro']='BIStro';
?>